### ISSUE TITLE
Avoid luacrypto

### ISSUE THREAD

**Issue by daurnimator** [remjey/luaotp#1]
luacrypto has been unmaintained for quite a while (https://github.com/mkottman/luacrypto/issues/39).
Would you mind swapping to e.g. [luaossl](http://25thandclement.com/~william/projects/luaossl.html) instead?

**Comment by remjey** [comment]
You’re right. I’ll release a version without this dependency today.

**Comment by remjey** [comment]
Luaotp now depends on luaossl instead of luacrypto.
